alg_name: "RoseLoRA"
model_name: "./hugging_cache/Qwen2.5-3B-Instruct"
device: 0

lora_type: "lora"
layers: []
num_steps: 25
batch_size: 1
max_length: 30
lr: 5e-4
weight_decay: 0
kl_factor: 0
rank: 8
lora_alpha: 32
lora_dropout: 0.1
norm_constraint: false
target_modules: ["q_proj", "k_proj", "v_proj", "o_proj"]
model_parallel: false

dtype: bfloat16 